on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  push: {}
name: e2e
jobs:
  integration:
    runs-on: ubuntu-latest
    if: (github.repository == 'kubernetes-sigs/cluster-api-provider-kubevirt') && contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: kubevirt/project-infra
          path: project-infra
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: kubeconfig
        run: 'echo -e "$KUBECONFIG" > $GITHUB_WORKSPACE/project-infra/.kubeconfig'
        shell: bash
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
      - name: Test
        run: |
          $GITHUB_WORKSPACE/project-infra/hack/mkpj.sh --job pull-kubernetes-sigs-cluster-api-provider-kubevirt-e2e --pull-number ${{github.event.number}} --kubeconfig $GITHUB_WORKSPACE/project-infra/.kubeconfig --trigger-job --fail-with-job
